changelog:
  exclude:
    authors:
      - renovate
    labels:
      - semver/ignore
  categories:
    - title: BREAKING CHANGES
      labels:
        - semver/breaking-change
    - title: New Features
      labels:
        - semver/enhancement
    - title: Other Changes
      labels:
        - "*"
