name: Check semver labels

on:
  pull_request_target:
    types:
      - labeled
      - unlabeled

jobs:
  check:
    runs-on: ubuntu-latest
    timeout-minutes: 1
    steps:
      - run: |
          [ ${{ contains(github.event.pull_request.labels.*.name, 'semver/*') }} == "true" ] || exit 1
