name: Check semver labels

on:
  pull_request_target:
    types:
      - opened
      - labeled
      - unlabeled

jobs:
  check:
    runs-on: ubuntu-latest
    timeout-minutes: 1
    steps:
      - run: |
          ${{ contains(join(github.event.pull_request.labels.*.name, ','), 'semver/') }} || exit 1
